#!usr/bin/env php
<?php

require 'vendor/autoload.php';

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;

class RouteCommand extends Command {
	
	protected function configure() {
		$this->setName('make:route')
			->setDescription('Generate a new route')
			->addArgument(
				'name',
				InputArgument::REQUIRED
			);
	}
	

	protected function execute(InputInterface $input, OutputInterface $output) {
		$routeName = $input->getArgument('name');
		
		if($routeName) {
			$output->writeln("<info>new controller {$routeName}</info>");
		} else {
			$output->writeln("<error>blank controller</error>");
		}
	}
}

class ModelCommand extends Command {
	protected function configure() {
		$this->setName('make:model')
			->setDescription('Generate a new model')
			->addArgument(
				'name',
				InputArgument::REQUIRED
			);
	}
}

$argv = new ArgvInput();
$command = $argv->getFirstArgument();
$application = new Application();

if(!$command || $command === 'help' || $command === 'h') {
	echo "List of commands";
}

switch ($argv->getFirstArgument()) {
	case 'make:route':
		# generate route
		break;
	case 'make:model':
		# generate model
		break;
	case 'make:view':
		# generate Twig view
		break;
	default:
		# error...
		break;
}

#
#$application->add(new MakeCommand());
#$application->run();